# Generated by Django 5.0 on 2023-12-30 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_alter_article_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='update',
            new_name='updated',
        ),
    ]
